#!/usr/bin/env ruby

require 'fileutils'
require 'erb'
require 'json'
require_relative 'lib/nginx_config'

TEMPLATE     = File.join(File.dirname(__FILE__), 'templates/nginx.conf.erb')
USER_CONFIG  = 'static.json'
NGINX_CONFIG = 'config/nginx.conf'

json = File.exist?(USER_CONFIG) ? JSON.parse(File.read(USER_CONFIG)) : {}
erb  = ERB.new(File.read(TEMPLATE)).result(NginxConfig.new(json).context)
File.write(NGINX_CONFIG, erb)
